version: 2
jobs:
  build:
    working_directory: /go/src/github.com/segmentio/oauth2_proxy
    docker:
      - image: segment/circleci-golang:1.10
    steps:
      - checkout
      - run:
          command: |
            TAG=`git rev-parse --short=7 HEAD`
            EXISTING_IMAGE=e6feea0
            docker pull $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/oauth2-proxy:$EXISTING_IMAGE
            docker tag $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/oauth2-proxy:$EXISTING_IMAGE $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/oauth2-proxy:$TAG
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/oauth2-proxy:$TAG
      - store_artifacts:
          path: .run
          destination: trebuchet

workflows:
  version: 2
  run:
    jobs:
      - build:
          filters:
            tags: { only: /.*/ }
